### ISSUE TITLE
19.02.2022 task haqqında

### ISSUE THREAD

**Issue by Rovshen98** [GulsenZalova/PragmatechFrontendProject#3]
Tapşırıq yerinə yetirilib. Button transition versəz daha yaxşı olar. Original Uİ-da yuxarıdakı 3 ədəd icon hover olanda animasiya ilə aşağı düşür. Bunu transform:translateY ilə edə bilərsiniz. Responsivelik də yazılsa daha yaxşı olar

**Comment by GulsenZalova** [comment]
Təşəkkür edirəm.
