### ISSUE TITLE
Task Haqqında 26.02.2022

### ISSUE THREAD

**Issue by Rovshen98** [GulsenZalova/PragmatechFrontendProject#4]
Demo1 - Hər şey əladır. Tək problem mousu qutunun üzərindən çəkəndə animasiya dərhal itir. Bunun qarşısını transition verməklə ala bilərsiniz
Demo2 - Hər şey yaxşıdır. Amma buttona color:lightgrey vermisiniz və bu buttonun rəngini solğun göstərir
Demo3 - Dizayn yaxşıdır. Amma animasiya originaldakı animasiyadan fərqlidir. 
Demo4 - Hər şey yaxşıdır. Amma hover olanda buttondakı background-color açıq rəngdə olmalıdır
Demo5 - Hər şey yaxşıdır. Background-color bir az tünddür. 
Demo6 - Əladır. Arxadakı rəqəmlərin yuxarı qalxmasına transition versəz daha yaxşı olar
Demo7 - Yaxşıdır. Buttonların üzərinə gələndə cursor:pointer olsa daha yaxşı olar
Demo8 - Normalda qutunun üzərində qırmızı zolaq olmamalıdır. hover olanda isə sağdan sola qırmızı zolaq gəlməlidir.Button simmetrik deyil, qutunun bir az solunda yerləşir. qutunun ortasında olsa daha yaxşı olar
Demo9 - Hər şey yaxşıdır. Buttonu qutunun ortasına çəksəz daha yaxşı olar

**Comment by GulsenZalova** [comment]
Təşəkkürlər
